using ProjectEuler;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ExceptionServices;
using System.Text;
using System.Threading.Tasks;

namespace Project_Euler
{
    internal class Problem2
    {
        public static void description()
        {
            Console.WriteLine("\tProblem 2: Even Fibonacci Numbers\n");
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms.");
            Console.WriteLine("By starting with 1 and 2, the first 10 terms will be: \n");
            Console.WriteLine("\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n");
            Console.WriteLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million, \n" +
                            "find the sum of the even-valued terms.\n");
        }

        public static void solve()
        {
            int fib = 2;
            int sum = 0;
            int temp = 0;
            while(fib < 4000000) //while num less than 4 million
            {
                sum += fib; //0 + 2 = 2
                int swap = fib; //swap = 2
                fib = 4 * fib + temp; //fib = 4 * 2 + 0 ---> fib = 8
                temp = swap; //temp == 2
                /*Console.Write(fib + ", " +
                             sum + ", " +
                             swap + ", " +
                             temp + "\n"); */  
            }
            Console.WriteLine("\n\tSolution:");
            Console.WriteLine("The sum of even-valued terms in a Fibonacci sequence that does not exceed four million is: " + sum);
        }

        public static void run()
        {
            description();
            solve();
            Program.promptContinue();
        }
    }
}
